In [1]:
### we have to apply feature scalining in svr because we dont have direct equation where coeff multiplying eacch of the features therefore not compenssating
###lower values for the feature taking high values

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv('Position_Salaries.csv')
x=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1].values

In [4]:
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [5]:
## we have to apply feature scaling on dependent variable also because its value is in thousands

In [6]:
y


array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

my x is 2d array and y is vector or 1d array and featuring scaling requires a matrix of features of 2d arrays

y=y.reshape(len(y),1)

i have to reshape and it takes two agument 1st is row therefore i take len(y) means jitni bhi row hogi usme apply ho jayega and second is column means 1 column bna do sabka

In [7]:
y =y.reshape(len(y),1)

In [8]:
y


array([[  45000],
       [  50000],
       [  60000],
       [  80000],
       [ 110000],
       [ 150000],
       [ 200000],
       [ 300000],
       [ 500000],
       [1000000]])

In [9]:
from sklearn.preprocessing import StandardScaler
sc_x =StandardScaler()
sc_y =StandardScaler()
x=sc_x.fit_transform(x)
y=sc_y.fit_transform(y)


Creating two separate StandardScaler objects for x and y is necessary when you need to scale both the input features (x) and the target variable (y). This is especially important when the ranges of x and y are different and need to be scaled independently.

Why Two StandardScaler Objects?
Independent Scaling: x and y are generally on different scales, and they need to be scaled independently. Each StandardScaler object maintains its own mean and standard deviation, which are used to scale the data

When the ranges of x and y are different, it means that the numerical values of the input features (x) and the target variable (y) vary on different scales. For example, the features might range from 1 to 10, while the target variable might range from 1.5 to 91.5, as shown in the previous example. This difference in scale can affect the performance of machine learning models, particularly those that rely on distance metrics or optimization algorithms that are sensitive to the scale of the data.

In [10]:
x

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [11]:
y

array([[-0.72004253],
       [-0.70243757],
       [-0.66722767],
       [-0.59680786],
       [-0.49117815],
       [-0.35033854],
       [-0.17428902],
       [ 0.17781001],
       [ 0.88200808],
       [ 2.64250325]])

In [12]:
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')
regressor.fit(x,y)

C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [13]:
regressor.predict(sc_x.transform([[]]))

ValueError: Found array with 0 feature(s) (shape=(1, 0)) while a minimum of 1 is required by StandardScaler.